### ISSUE TITLE
Short side dogbone ( or T bone) not working

### ISSUE THREAD

**Issue by Chrisc1964** [DVE2000/Dogbone#68]
I love the add-in, thank you.  But I am having trouble with the T bone option.   Both the dog bone and minimal options work fine, but no such luck with the short side option which seems to be called T-bone in other add-ins.  A friend pulled the logs for it and it seems to be hitting an internal error while trying to access StartingVertex (or something similar).   If not a bug, then I'd much appreciate any guidance on how I can make it work.

Thanks

BTW: using Fusion 2.0.20981 x86_64 on a WIn11 AMD PC.  Tried it on two different machines, same results

**Comment by pludikar** [comment]
Hi,

I suspect that it may be a bug.  I had a few issues with this a while back and I thought I fixed it.  However, I know I don’t always catch and fix everything. Give me a day or so, and I’ll get back to you with a solution

Regards
Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chrisc1964 ***@***.***>
Sent: Friday, January 24, 2025 6:49:25 PM
To: DVE2000/Dogbone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DVE2000/Dogbone] Short side dogbone ( or T bone) not working (Issue #68)


I love the add-in, thank you. But I am having trouble with the T bone option. Both the dog bone and minimal options work fine, but no such luck with the short side option which seems to be called T-bone in other add-ins. A friend pulled the logs for it and it seems to be hitting an internal error while trying to access StartingVertex (or something similar). If not a bug, then I'd much appreciate any guidance on how I can make it work.

Thanks

**Comment by pludikar** [comment]
hi @Chrisc1964,

I think I found the issue and I've uploaded a new version.  I've not updated the Git version yet, but the files are available by downloading the .zip from the code button on the Git main page.

Let me know if there are still issues - you'll be my Guinea pig :)

Regards
Peter

**Comment by pludikar** [comment]
Sorry - I spoke too soon.  I broke something else.  I'll let you know as soon as I've unbroken it.

Peter

**Comment by pludikar** [comment]
I think I've fixed it.  Let me know if you find anything to the contrary

Peter

**Comment by Chrisc1964** [comment]
The fix appears to be working - thank you!  However, I don't understand what "Depth Extent" does as I can not get it do anything when the first option is selected.  The dogbones only show up when the second option is selected.  Can you explain how and what it is supposed to do?  Thanks, Chris

**Comment by pludikar** [comment]
Hi,

In principle, the depth extent mode will affect the length of the dogbone.  If you have an eligible dogbone corner that doesn't extend the whole depth of the material eg from the bottom to half way up, then "from selected face" will generate the dogbone from the bottom of the corner to the selected face; whereas "from top face" will generate the dogbone from the bottom of the corner to the top face of the material whether of not the corner extends to the top or not.

However, I found that this is another bug and I've got more work to do 🙁  I'll let you know when I've addressed it.

Peter


________________________________

**Comment by pludikar** [comment]
Hi,

I believe I've fixed the Depth Extent issue and the new version have been uploaded to Git.

This is what the "to Selected Face" does:

![Image](https://github.com/user-attachments/assets/abb9e9b8-dc6e-4934-bf12-10ed22902098)

and this is what the "to Top Face" does:

![Image](https://github.com/user-attachments/assets/1fb22a73-fd42-4288-82e8-8d3dd140de2d)

The use case for the "to Selected Face" is relatively limited; you either need a special router tool to access the dogbone, or you machine the dogbone from the bottom side (ie you do 2 sided machining).  I'm not 100% sure why I included the mode choice but I'm leaning to deprecating it sometime in the future.  There may be other use cases I'm not aware of, so I'm leaving it in for the time being.

Peter

**Comment by pludikar** [comment]
Hi @Chrisc1964,

If you're still interested - I've added a preview mode (under settings) and updated the files appropriately.

Hopefully everything should be working without issue

Peter

**Comment by Chrisc1964** [comment]
Thanks – Just used your latest for a small project – it worked well but seems to still have a small bug.  If preview mode was on(default) then I was unable to select the face of my component.  Once I clicked preview off, I was able to select the face and the dogbones worked as they should.

 

Thanks Again for an excellent add-in

**Comment by pludikar** [comment]
@Chrisc1964 

Ah!   It's a feature and not a bug - I can change it if needed.  I had a couple of options when I added the preview, maybe I made the wrong choice, you can tell me if I did. .

If you use fillet, chamfer or draft features in design you have to use ctrl click to select additional faces and/or edges after the initial selection.  I basically did exactly the same, except I went for the option of needing the ctrl button to be active on every face selection.  A tool tip should appear when you move the mouse to say that, but I guess it's not as obvious as I thought it was.

So, at the moment, you **must** press the ctrl button, even for the 1st selection.  I found the selection in fillet/chamfer and draft to be awkward and I've now ended up using ctrl click for everything because I don't need to think about whether ctrl should be active or not.

Preview in F360 does funny things to the models because it effectively replaces every face of previewed bodies and it becomes a challenge to figure out which faces and edges the add-in is actually working on.  The ctrl button does little more than disables the preview mode and reverts the view to the original model. 

If you happen to not be aware of it, you can click on the edges selection box (2nd row in the dialog box) and then you can select or deselect dogbone edges individually (using ctrl click as well here).

Peter

**Comment by Chrisc1964** [comment]
Love it – didn’t know about holding down the control!  Thanks, Chris
